baseURL = 'https://the-king-of-comedy.github.io/'
languageCode = 'zh-cn'
title = 'the king of comedy'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    showCodeCopyButtons = true
    # 开启搜索功能
    ShowReadingTime = true
    DateFormat = "2006-01-02 15:04:05"
    description = '记录技术学习与日常折腾的个人博客'

[taxonomies]
    tag = "tags"

[outputs]
    home = ["HTML", "RSS", "JSON"] # 搜索功能需要 JSON 输出

[[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20